- _assets/stylesheets/_layout/_header.scss
- _assets/stylesheets/_redbat/_forms.scss
- _includes/header.html
> 33 Add by Me

- atom.articles.xml
- atom.xml
Displaying the art directed posts in the right way.
> Feed fix for art directed articles

- _assets/stylesheets/_layout/_footer.scss
- _assets/stylesheets/_layout/_header.scss
- _assets/stylesheets/_layout/_maincontent.scss
- _assets/stylesheets/_layout/_pages.scss
- _assets/stylesheets/_redbat/_bits.scss
- _assets/stylesheets/_redbat/_buttons.scss
- _assets/stylesheets/_redbat/_forms.scss
- _assets/stylesheets/_redbat/_images.scss
- _assets/stylesheets/_redbat/_pagenavi.scss
- _assets/stylesheets/_redbat/_type.scss
- _posts/2016-01-19-flexbox-newsletter-form.md
Changes color variables to new syntax of `$lowercase-variable`. Addresses issue #48.
> 48 fix color variable format

- .codeclimate.yml
- _assets/stylesheets/_redbat/_syntax.scss
Trying to fix the syntax stylesheet to meet CodeClimate standards
None.
None.
None.
:coffee:
#62
> Adding semicolon and making comments nicer

- .codeclimate.yml
- _assets/stylesheets/_layout/_maincontent.scss
Basically making main content CSS way nicer.
:coffee:
Addresses both #56 and #57
> Fixing up maincontent

- .codeclimate.yml
- _assets/stylesheets/_layout/_header.scss
- _posts/2013-10-03-review-1password-4-for-mac.md
Fixing trailing spaces
:coffee:
Fixes #63.
> Fixing trailing for 1password 4 review

- _assets/stylesheets/_redbat/_type.scss
> Refactoring type stylesheet

- _assets/stylesheets/_layout/_footer.scss
> Fixing up for CodeClimate :boom:

- _assets/stylesheets/_layout/_pages.scss
Refactoring. Also changing the look of the topics list.
:coffee:
#72
> refactoring. Also changing topics list styles

- _assets/javascripts/search.js
- _assets/stylesheets/_layout/_header.scss
- _assets/stylesheets/_redbat/_buttons.scss
- _assets/stylesheets/_redbat/_forms.scss
- _includes/header.html
Search doesn't always have to be present, so I'm hiding it.
:coffee:
> Redesigning search

- _includes/date.html
- _includes/tags.html
- _layouts/post.html
- index.html
- tags.html
Downcasing and hyphenating links and ids for tags. #83 
:coffee:
> 83 Tag Fixes

- Gemfile.lock
- _assets/stylesheets/_layout/_pages.scss
- _layouts/archives.html
- _posts/2016-03-16-apple-its-time-to-move-on-from-os-x-by-pauli-olavi-ojala.markdown
- tags.html
- Update Lunr Search Gem
- Update style for entries across topics, archives, search results
- Update a post that wasn't title cased (*I know, I know. I shouldn't do this*)
:coffee:
> Updating Lunr Search Gem

- Rakefile
Cleaning up the Rakefile
:coffee:
#46
> Cleaning up the rakefile

- .codeclimate.yml
- _assets/stylesheets/_redbat/_pagenavi.scss
- _assets/stylesheets/global.css.scss
- _assets/stylesheets/ulysses-give-up.css.scss
- index.html
Working on:
- #73 
- #75 
- #77 
:coffee:
> Refactor more stylesheets

- _assets/stylesheets/_layout/_footer.scss
- _assets/stylesheets/_layout/_header.scss
- _assets/stylesheets/_layout/_maincontent.scss
- _assets/stylesheets/_redbat/_bits.scss
- _assets/stylesheets/_redbat/_forms.scss
- _assets/stylesheets/_redbat/_objects.scss
- _includes/header.html
Redesign the Header to include search on mobile devices and clean it up a little.
:coffee:
> Redesigning Header

- _assets/stylesheets/_redbat/_images.scss
Refactor `.rightalign` and `.leftalign` to use Flexbox.
:coffee:
> Refactor images

- _assets/stylesheets/_redbat/_type.scss
- _includes/head.html
Making `ol`s and `ul`s 100% within `blockquote`.
:coffee:
> Small fixes 081216

- .travis.yml
- Gemfile
- Gemfile.lock
- Rakefile
`html-proofer` can jump off a cliff.
:coffee:
> remove Travis CI because it’s too much

- README.md
Removed the status badge and got carried away.
:coffee:
> remove build status and add more contributing guidelines

- _assets/stylesheets/_layout/_pages.scss
- _layouts/page.html
- tags.html
Adding those "back to top" links cuz it's driving me nuts.
:coffee:
> add anchors to topics page

- _layouts/custom-post.html
- _layouts/page.html
- _layouts/post.html
- index.html
Smarty pants-ing page and post titles.
:coffee:
> smartify page and post titles

- _assets/stylesheets/_redbat/_syntax.scss
- _assets/stylesheets/_redbat/_type.scss
Changing syntax highlighting theme.
:coffee:
> Syntax highlighting experiments

- _config.yml
- _config_production.yml
- atom.articles.xml
- atom.xml
- subscribe.html
Some small feed improvements.
:coffee:
> Feed improvements

- _assets/stylesheets/_redbat/_syntax.scss
Trying to improve the `code` tags.
:coffee:
> improve look of code tags

- _assets/stylesheets/_redbat/_syntax.scss
- _posts/2015-06-29-hosting-a-jekyll-site-on-heroku.md
- styleguide.md
Still wasn't happy with the syntax theme, so changing it yet again.
:coffee:
> Syntax theme improvements

- _assets/stylesheets/_redbat/_syntax.scss
- _config.yml
- _posts/2015-12-01-switching-to-redcarpet.md
- _posts/2016-08-16-im-an-impostor--david-walsh-blog.markdown
I'm looking to switch to Kramdown to improve the performance of the render. I'm only seeing about a second of difference though. Still at 14 seconds.
:coffee:
> render markdown with Kramdown

- about.md
> update about page

- _posts/2016-09-15-apple-removing-ports-from-macbook-pro.markdown
Sorry about the weird branch name. Autocorrect apparently strikes again.
> Add Blog Post - Apple Removing Ports from MacBook Pro?

- _assets/stylesheets/_layout/_maincontent.scss
- _assets/stylesheets/_redbat/_type.scss
`text-decoration` is so ugly. I finally got fed up.
:coffee:
> use border-bottom for links instead of text-decoration

- _assets/stylesheets/_layout/_header.scss
- _assets/stylesheets/_layout/_maincontent.scss
- _assets/stylesheets/_redbat/_type.scss
- _assets/stylesheets/editor-style.css.scss
- _assets/stylesheets/on-inspiration.css.scss
- _assets/stylesheets/ulysses-give-up.css.scss
- _includes/small-author.html
- _layouts/custom-post.html
- _posts/2016-02-10-on-inspiration.md
- Add author info to art direction post type
- Fixing some legacy styles in the art directed posts
:coffee:
> Add author info to art direct type

- Gemfile
- Gemfile.lock
- _config.yml
- _config_production.yml
- _posts/2016-09-22-design-as-branding-daring-fireball.md
- Getting opinion about the Design as Branding post
- Adding `Jekyll::Compose` plugin to make it easier for contributors.
:coffee:
> Design as branding

- _posts/2013-10-18-freelancing-and-saying-no.md
- _posts/2016-03-26-my-very-brief-review-of-batman-v-superman-dawn-of-justice.md
- _posts/2016-04-26-my-brief-review-of-the-iphone-6s-plus.markdown
- _posts/2016-08-17-my-brief-review-of-shush-app.markdown
- Adding a new tag for `Brief Review`. This is a new series I'd like to expand on.
- Updating a post that was still using `h3` to use `h2` within the post body.
:coffee:
> Small Post Updates

- _assets/stylesheets/_layout/_maincontent.scss
- _assets/stylesheets/_redbat/_forms.scss
- _includes/newsletter-form.html
- Fix the layout of the newsletter on smaller screens.
- Increase line-height on link header and give some space
#134 
:coffee:
> 134 Fix Newsletter

- _data/authors.yml
> Fix grammar using “a” before word starting with vowel

- _data/authors.yml
Adding Sonya to authors list as Editor. 
:coffee:
> Add Sonya to authors list

- about.md
Changing gravatar src from:
`http://gravatar.com`
to
`//gravatar.com`
:coffee:
> Change gravatar requests to relative

- atom.articles.xml
- atom.xml
- Fixing feed subtitle
:coffee:
> Add Tim and Friends as subtitle

- Gemfile
- Gemfile.lock
- _assets/stylesheets/_layout/_header.scss
- _assets/stylesheets/_redbat/_type.scss
- Increasing font size on smaller screens.
:coffee:
> 144 increase font size

- .codeclimate.yml
- _posts/2016-10-06-display-spaces-and-the-dock.md
Complain about the Mac Dock and Switcher
I snapped this morning when it happened to me again for the 1,000,000,000123,432,3432342 time
I drank beer every evening for the last three days
:coffee:
> Add post about the Mac Dock and Switcher

- _assets/stylesheets/_layout/_footer.scss
- _assets/stylesheets/_layout/_header.scss
- _assets/stylesheets/_layout/_maincontent.scss
- _assets/stylesheets/_redbat/_bits.scss
- _assets/stylesheets/_redbat/_type.scss
- _assets/stylesheets/ulysses-give-up.css.scss
- _includes/header.html
- _includes/search-form.html
Wasn't liking the new colors I went with so I moved back.
> Reverting colors back to original

- _assets/stylesheets/_layout/_footer.scss
- _includes/footer.html
- _includes/head.html
Fix styles that were a little weird once the newsletter form was removed.
:coffee:
> Footer fixes

- _assets/stylesheets/_redbat/_type.scss
https://app.clubhouse.io/towermedia/story/35/fix-lists-in-blockquotes
:coffee:
> Reduce space in blockquote for ordered/unordered lists

- atom.articles.xml
- atom.xml
https://app.clubhouse.io/towermedia/story/38/eliminate-categories-as-a-necessary-part-of-the-front-matter
:coffee:
> Use custom type instead of categories

- config.ru
Improve the caching and gzip on the site.
:coffee:
> Improve Caching and Gzip

- _assets/stylesheets/_redbat/_type.scss
<sup>Super small fix for superscript</sup> haha
:coffee:
> Update styles for superscript

- _includes/full-author.html
Updated protocol on Gravatar images.
:coffee:
> Update protocol on gravatar images

- _assets/stylesheets/_layout/_pages.scss
- _assets/stylesheets/_redbat/_type.scss
- tags.html
I wanted the topics page to be a bit more helpful, and I didn't like the way the info was displayed.
:coffee:
> Redesign the Topics Page

- _includes/footer.html
- _includes/head.html
Moving away from Segment code and putting it all the way at the bottom
:coffee:
> Switch to google tracking code

- _layouts/tags_json.html
- _plugins/autotag_gen.rb
> Add jTag templates

- Rakefile
Remove the `pub` command from the Rakefile because I don't ever use/need it anymore.
:coffee:
> Remove the pub command from Rakefile

- _posts/2017-02-28-hot-macbook-pro.markdown
- _posts/2017-03-10-hot-macbook-pro.markdown
Add a blog post about my MacBook Pro running hot and how I fixed it.
I don't like my system running hot or having performance issues on my MacBook Pro
I used to shoe horses — wait, that's not relevant
I don't have any
:coffee:
(I don't drink coffee, am I still allowed to be here?)
> Blog post/hot macbook pro
